### ISSUE TITLE
railway logs -d commend gives TLS error

### ISSUE THREAD

**Issue by SunGunes** [railwayapp/cli#396] opened 2023-03-23 13:00 UTC
I am trying to get the production logs from my computer but im getting TLS error?
railway logs -d

Error: TLS error: webpki error: UnsupportedCriticalExtension

Caused by:
    0: webpki error: UnsupportedCriticalExtension
    1: UnsupportedCriticalExtension
    
    Is this because of me or general problem ? 
    Thank you!
    Have a nice day!

**Comment by coffee-cup** [comment] 2023-04-26 20:35
I believe this is an issue with your network. I am unable to reproduce and it doesn't seem to be an issue that others are having. Closing for now

**Closed by coffee-cup** 2023-04-26 20:35 UTC

**Comment by AlexJBlair** [comment] 2023-05-10 07:49
I have run into this issue as well. I am not really doing anything special as far as network security and I simply ran the command `railway up`.
